export const spacing = {
  zero: '0rem',
  xxs: '.2rem',
  xs: '.4rem',
  base: '.8rem',
  basePlusXs: '1.2rem',
  sm: '1.6rem',
  smPlusXs: '2rem',
  smPlusBase: '2.4rem',
  smPlusBasePlusxs: '2.8rem',
  md: '3.2rem',
  mdPlusXs: '3.6rem',
  mdPlusBase: '4rem',
  mdPlusBasePlusXs: '4.4rem',
  mdPlusSm: '4.8rem',
  mdPlusSmPlusXs: '5.2rem',
  xl: '6.4rem',
  xlPlusBase: '7.2rem',
  xxlMinusBase: '12.0rem',
  xxl: '12.8rem',
  xxlPlusBasePlusXs: '14.0rem',
  xxxlMinusMdPlusXs: '22rem',
  xxxlMinusMd: '22.4rem',
}
